# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f4bc2f95c8e0456857eb935619b7d1ccbd0f05ba672fac39603f119b8aaa10f3a8b49375a2325c8225fbd0595ad6c645724c080ab59cbafa4df011cef0c45076

test:
  secret_key_base: f83ac14db7a411132a6428a9d270d8906a694be1a8a073e9f0327041ba76b355744272fbd29acdce8baa47ff79c45ce072dc96066ba1ff5e3dc6a7eb4ff9a779

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
